sudo: false
cache: bundler
language: ruby

rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0

before_install:
  - gem install bundler -v 2.0.2

gemfile:
  - gemfiles/activemodel_4.2.gemfile
  - gemfiles/activemodel_5.2.gemfile
  - gemfiles/activemodel_6.0.gemfile
